services:
  app:
    image: myapp:dev
    build:
      context: .
      dockerfile: Dockerfile
      target: gobuilder
      args:
        VERSION: $VERSION
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./app:/app
    environment:
      - GIN_MODE=debug
    deploy:
      replicas: 1
  
  web:
    image: tco:web
    build:
      context: .
      dockerfile: Dockerfile
      target: nodebuilder
      args:
        VERSION: $VERSION
    volumes:
      - ./web:/web
    command: sh -c 'npm install && npm run dev -- --host'
